install: add dependency installer

diff --git a/install b/install
--- a/install
+++ b/install
@@ -7,6 +7,43 @@ HOME_DIR="$HOME"
 STATE_DIR="${XDG_STATE_HOME:-$HOME/.local/state}/dotfiles"
 STAMP_FILE="$STATE_DIR/.initialized"
 
+DEPS=(
+    stow
+    zsh
+    tmux
+    neovim
+    alacritty
+    rofi
+    grim
+    slurp
+    swappy
+    mangohud
+    blueman
+    wl-clipboard
+    cliphist
+    fish
+    qt5-wayland
+    qt6-wayland
+    zoxide
+    starship
+    xdg-desktop-portal
+    xdg-desktop-portal-hyprland
+    xdg-desktop-portal-gtk
+    network-manager-applet
+    dolphin
+    kitty
+    swaync
+    hyprshot
+    hyprpaper
+    hyprshutdown
+    waypaper
+    wayle
+    hyprpolkitagent
+    ghostty
+    brave-bin
+    matugen
+)
+
 log() {
     printf "\e[1;32m[dotfiles]\e[0m %s\n" "$*";
 }
@@ -16,8 +53,34 @@ log_die() {
     exit 1
 }
 
+log_warn() {
+    printf "\e[1;33m[dotfiles]\e[0m %s\n" "$*"
+}
+
 require() {
     command -v "$1" &>/dev/null || log_die "'$1' is not installed."
+}
+
+install_deps() {
+    if [[ -f "${STAMP_FILE}" ]]; then
+        log_warn "dotfiles has already been initialized."
+        log_die "exiting.."
+    fi
+
+    # Install yay if missing
+    if ! command -v yay &>/dev/null; then
+        log "yay not found. Installing yay from AUR..."
+        local tmp_dir
+        tmp_dir="$(mktemp -d)"
+        git clone --depth=1 https://aur.archlinux.org/yay-bin.git "$tmp_dir"
+        (cd "$tmp_dir" && makepkg -si --noconfirm)
+        rm -rf "$tmp_dir"
+    fi
+
+    log "Installing dependencies..."
+    yay -S --needed --noconfirm "${DEPS[@]}"
+
+    log "Installed required dependencies."
 }
 
 init_matugen() {
@@ -50,6 +113,8 @@ check_wallpaper_folder() {
 }
 
 stow_it() {
+    install_deps
+
     require "stow"
     require "matugen"
 
